os: osx
osx_image: xcode13.3
language: swift
script: xcodebuild clean build test -workspace "second.xcworkspace" -scheme "secondci" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=15.4,name=iPhone 11" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO



